services:
  waha:
    image: devlikeapro/waha:chrome
    container_name: waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_DEFAULT_ENGINE=${WHATSAPP_DEFAULT_ENGINE}
      - WAHA_DASHBOARD_NO_PASSWORD=True
      - WHATSAPP_API_KEY=${WAHA_API_KEY}

        # Add webhook config
      - WHATSAPP_HOOK_URL=http://waha-webhook:3001/waha-webhook
      - WHATSAPP_HOOK_EVENTS=message
    volumes:
      - ./.waha:/app/.waha
    networks:
      - default
      - openclaw_net

  waha-webhook:
    build: .
    image: ashfaq357/ash-whatsapp-bot:latest
    container_name: waha-webhook
    restart: unless-stopped
    environment:
      - OPENCLAW_URL=${OPENCLAW_URL}
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_URL=${WAHA_URL}
    depends_on:
      - waha
    networks:
      - default
      - openclaw_net

networks:
  openclaw_net:
    external: true
    name: openclaw_default
